version: 2
updates:
- package-ecosystem: nuget
  directory: "/tests"
  schedule:
    interval: weekly
    time: "21:00"
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: weekly
    time: "21:00"